#!/usr/bin/env bash

LATEST_VERSION="5"

if [ "$DOCKER_TAG" = "latest" ]; then
	PHPVERSION=$LATEST_VERSION
else
	PHPVERSION=$DOCKER_TAG
fi

docker build -t ${IMAGE_NAME} \
	--build-arg=PHPVERSION=$PHPVERSION \
	--build-arg=DOCKER_TAG=$DOCKER_TAG \
	.
